### ISSUE TITLE
Some tweaks against the default config.nu

### ISSUE THREAD

**Issue by hyrious** [stevenxxiu/sublime_text_nushell#2]
I just played around with the sublime-syntax file but having no time to improve it and change test cases, it has fixed many visual bugs by simply looking at the default config.nu:

_Before_: 
<img width="408" alt="image" src="https://user-images.githubusercontent.com/8097890/210341630-bf8ce5fd-c891-423b-9552-dfc957830f78.png">

_After_: 
<img width="406" alt="image" src="https://user-images.githubusercontent.com/8097890/210341672-9cdbb35b-37db-472b-bee9-5d9ff96c8c0d.png">

So I will just post the final file and diff here for your inspiration.

[packed.tar.gz](https://github.com/stevenxxiu/sublime_text_nushell/files/10335919/packed.tar.gz)

**Comment by stevenxxiu** [comment]
Hi thanks for the issue.

I took a look at your diff before, but it was a bit big and tricky to parse. Especially when some lines have been commented out.

I've put in a lot of changes into the syntax highlighter recently, so this might be out-of-date.

Please re-open if the latest `master` is still broken, and post a broken example in text form.

I'm closing this for now.
