### ISSUE TITLE
Keywords are not detecting word boundaries

### ISSUE THREAD

**Issue by princemaple** [stevenxxiu/sublime_text_nushell#3]
![image](https://user-images.githubusercontent.com/1329716/211146934-68fc9d30-0001-4d2a-8f04-2881fc138980.png)

**Comment by stevenxxiu** [comment]
I've been working on the syntax highlighter a bit more lately, with lots of new changes.

This should now be fixed in `master`.

**Comment by princemaple** [comment]
Looks much better now ❤️ thanks!
